// <auto-generated />
using GradeCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeCalculator.Migrations
{
    [DbContext(typeof(GradeCalculatorContext))]
    [Migration("20221216132117_Initial create")]
    partial class Initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradeCalculator.Models.GCalculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Average_Mark")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Student_Dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Student_Regno")
                        .HasColumnType("int");

                    b.Property<int>("Subject1_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Subject2_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Subject3_Mark")
                        .HasColumnType("int");

                    b.Property<int>("Total_Mark")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GCalculator");
                });
#pragma warning restore 612, 618
        }
    }
}
